#include "file_format.hpp"
#include "vg.pb.h" // Generated by protoc
#include <zlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <google/protobuf/io/zero_copy_stream_impl.h>
#include <google/protobuf/io/gzip_stream.h>
#include <iostream>
#include <vector>
#include <string>
#include <unordered_set>
#include <algorithm>
#include <chrono>
#include <sstream>
#include <stdexcept>
#include <atomic>

// Buffer size for zlib-based gzip reading
constexpr int GZIP_BUFFER_SIZE = 128 * 1024;


// Helper to read a varint from a stream
bool read_varint(google::protobuf::io::ZeroCopyInputStream& stream, uint64_t& value) {
    const void* data;
    int size;
    value = 0;
    uint8_t byte;
    int shift = 0;
    do {
        if (!stream.Next(&data, &size) || size == 0) return false;
        byte = *static_cast<const uint8_t*>(data);
        stream.BackUp(size - 1);
        value |= (uint64_t)(byte & 0x7F) << shift;
        shift += 7;
    } while (byte & 0x80);
    return true;
}

// Processes a single alignment protobuf message
std::unordered_map<int64_t, std::vector<Segment>> process_alignment(
    const vg::Alignment& aln,
    const std::unordered_set<int64_t>& wanted_nodes,
    const std::string& chrom_filter)
{
    std::unordered_map<int64_t, std::vector<Segment>> segment_dict;

    if (aln.mapping_quality() <= 10) return segment_dict;
    if (!chrom_filter.empty()) {
        bool found = false;
        for (const auto& pos : aln.refpos()) {
            if (pos.name() == chrom_filter) {
                found = true;
                break;
            }
        }
        if (!found) return segment_dict;
    }

    int read_offset = 0;
    for (const auto& mapping : aln.path().mapping()) {
        int64_t nid = mapping.position().node_id();

        if (wanted_nodes.find(nid) == wanted_nodes.end()) {
            for (const auto& edit : mapping.edit()) {
                read_offset += edit.to_length();
            }
            continue;
        }

        std::stringstream seq_ss, cigar_ss;
        std::string bq_parts;

        for (const auto& edit : mapping.edit()) {
            const int fL = edit.from_length();
            const int tL = edit.to_length();

            if (fL == tL) cigar_ss << fL << (edit.sequence().empty() ? 'M' : 'X');
            else if (fL > 0 && tL == 0) cigar_ss << fL << 'D';
            else if (fL == 0 && tL > 0) cigar_ss << tL << 'I';

            if (tL > 0) {
                std::string seq_frag = aln.sequence().substr(read_offset, tL);
                std::transform(seq_frag.begin(), seq_frag.end(), seq_frag.begin(), ::toupper);
                seq_ss << seq_frag;
                bq_parts.append(aln.quality().substr(read_offset, tL));
                read_offset += tL;
            }
        }

        segment_dict[nid].emplace_back(Segment{
            (int16_t)mapping.position().offset(),
            seq_ss.str(),
            bq_parts,
            cigar_ss.str(),
            (int16_t)aln.mapping_quality(),
            mapping.position().is_reverse() ? '-' : '+'
        });
    }
    return segment_dict;
}


// Packs a vector of segments into a binary buffer for writing
std::vector<char> pack_segments(const std::vector<Segment>& segments, const BlockInfo& info) {
    std::vector<char> buffer(segments.size() * info.record_size);
    char* current_pos = buffer.data();

    for (const auto& s : segments) {
        // Clear the record memory
        memset(current_pos, 0, info.record_size);

        char* ptr = current_pos;

        // Pack offset and rq
        memcpy(ptr, &s.offset, sizeof(s.offset));
        ptr += sizeof(s.offset);

        // Pack seq, bq, cigar (with padding/truncation)
        memcpy(ptr, s.seq.c_str(), std::min((size_t)info.max_read_len, s.seq.length()));
        ptr += info.max_read_len;

        memcpy(ptr, s.bq.c_str(), std::min((size_t)info.max_read_len, s.bq.length()));
        ptr += info.max_read_len;

        memcpy(ptr, s.cigar.c_str(), std::min((size_t)info.max_cigar_len, s.cigar.length()));
        ptr += info.max_cigar_len;

        memcpy(ptr, &s.rq, sizeof(s.rq));
        ptr += sizeof(s.rq);

        memcpy(ptr, &s.strand, sizeof(s.strand));

        current_pos += info.record_size;
    }
    return buffer;
}


void flush_segment_buffer(
    int fd,
    std::unordered_map<int64_t, std::vector<Segment>>& buffer,
    std::unordered_map<int64_t, BlockInfo>& block_infos
) {
    if (buffer.empty()) return;

    for (auto const& [nid, segments] : buffer) {
        auto it = block_infos.find(nid);
        if (it == block_infos.end()) continue;

        BlockInfo& info = it->second;
        std::vector<char> packed_data = pack_segments(segments, info);

        uint32_t records_written = info.current_pos.fetch_add(segments.size());
        uint64_t write_offset = info.file_offset + sizeof(BlockHeader) + (uint64_t)records_written * info.record_size;

        ssize_t bytes_written = pwrite(fd, packed_data.data(), packed_data.size(), write_offset);
        if (bytes_written != (ssize_t)packed_data.size()) {
             std::cerr << "Error writing to .dat file for node " << nid << std::endl;
        }
    }
    buffer.clear();
}


// Main pipeline function
void run_pipeline(
    const std::string& gam_path,
    const std::string& stats_path,
    const std::string& output_prefix,
    int milestone_step,
    const std::string& chrom_filter,
    bool use_existing)
{
    std::unordered_map<int64_t, BlockInfo> block_infos;
    std::unordered_set<int64_t> wanted_nodes;
    std::string dat_path = output_prefix + ".dat";
    std::string idx_path = output_prefix + ".idx";
    uint64_t total_file_size = 0;

    // Initialization
    if (use_existing) {
        // NOTE: A robust implementation would load existing files.
        // For simplicity, we are re-initializing. Add logic to read .idx/.dat here if needed.
        throw std::runtime_error("--use-existing is not fully implemented in this example. Please re-initialize.");
    } else {
        std::cout << "Initializing output files from TSV stats..." << std::endl;
        std::ifstream stats_file(stats_path);
        if (!stats_file) throw std::runtime_error("Cannot open stats file: " + stats_path);

        std::string line;
        // Skip header
        std::getline(stats_file, line);

        std::vector<std::tuple<int64_t, int, int, int>> stats_data;
        int64_t node_id;
        int n_records, max_read, max_cigar;
        while (stats_file >> node_id >> n_records >> max_read >> max_cigar) {
             stats_data.emplace_back(node_id, n_records, std::max(1, max_read), std::max(1, max_cigar));
        }

        std::sort(stats_data.begin(), stats_data.end()); // Sort by node_id for deterministic layout

        total_file_size = GLOBAL_MAGIC.length() + sizeof(GlobalHeader) + stats_data.size() * sizeof(BlockHeader);

        for (const auto& stat : stats_data) {
            node_id = std::get<0>(stat);
            wanted_nodes.insert(node_id);
            BlockInfo info;
            info.n_records = std::get<1>(stat);
            info.max_read_len = std::get<2>(stat);
            info.max_cigar_len = std::get<3>(stat);
            info.file_offset = total_file_size;
            info.record_size = sizeof(int16_t) + info.max_read_len + info.max_read_len + info.max_cigar_len + sizeof(int16_t) + sizeof(char);
            info.block_size = info.n_records * info.record_size + sizeof(BlockHeader);
            block_infos[node_id] = info;
            total_file_size += info.block_size - sizeof(BlockHeader);
        }

        // Write .dat file header and pre-allocate
        std::ofstream dat_file(dat_path, std::ios::binary);
        dat_file.write(GLOBAL_MAGIC.c_str(), GLOBAL_MAGIC.length());
        GlobalHeader g_header = {GLOBAL_MAJOR, GLOBAL_MINOR, (uint32_t)block_infos.size(), {0}};
        dat_file.write(reinterpret_cast<const char*>(&g_header), sizeof(g_header));

        for (const auto& stat : stats_data) {
            const auto& info = block_infos.at(std::get<0>(stat));
            BlockHeader b_header = {(uint32_t)std::get<0>(stat), info.n_records, 0, info.max_read_len, info.max_cigar_len};
            dat_file.write(reinterpret_cast<const char*>(&b_header), sizeof(b_header));
        }
        dat_file.close();
        // Pre-allocate file space
        int fd_dat = open(dat_path.c_str(), O_WRONLY);
        if (ftruncate(fd_dat, total_file_size) != 0) {
            throw std::runtime_error("Failed to pre-allocate .dat file.");
        }
        close(fd_dat);


        // Write .idx file
        std::ofstream idx_file(idx_path, std::ios::binary);
        uint32_t count = block_infos.size();
        idx_file.write(reinterpret_cast<const char*>(&count), sizeof(count));
        for (const auto& stat : stats_data) {
            const auto& info = block_infos.at(std::get<0>(stat));
            IndexEntry entry = {(uint32_t)std::get<0>(stat), info.file_offset, info.block_size, info.n_records, 0, info.max_read_len, info.max_cigar_len};
            idx_file.write(reinterpret_cast<const char*>(&entry), sizeof(entry));
        }
    }

    // Processing
    auto start_time = std::chrono::high_resolution_clock::now();
    long total_reads = 0;
    long next_milestone = milestone_step;

    int data_fd = open(dat_path.c_str(), O_WRONLY);
    if (data_fd == -1) throw std::runtime_error("Cannot open .dat file for writing.");

    std::ifstream raw_gam_file(gam_path, std::ios::binary);
    if (!raw_gam_file) throw std::runtime_error("Cannot open GAM file: " + gam_path);

    google::protobuf::io::IstreamInputStream zero_copy_input(&raw_gam_file);
    google::protobuf::io::GzipInputStream gzip_input(&zero_copy_input);

    std::unordered_map<int64_t, std::vector<Segment>> segment_buffer;
    size_t buffered_segments = 0;
    const size_t BUFFER_FLUSH_THRESHOLD = 500000;

    std::string buffer;
    vg::Alignment aln;
    uint64_t group_count;

    while (read_varint(gzip_input, group_count)) {
        if (group_count == 0) continue;
        uint64_t msg_size;

        for (uint64_t i = 0; i < group_count; ++i) {
             if (!read_varint(gzip_input, msg_size)) break;
             buffer.resize(msg_size);
             gzip_input.Read(&buffer[0], msg_size);

             if (aln.ParseFromString(buffer)) {
                total_reads++;
                auto new_segs = process_alignment(aln, wanted_nodes, chrom_filter);
                for (auto const& [nid, segs] : new_segs) {
                    segment_buffer[nid].insert(segment_buffer[nid].end(), segs.begin(), segs.end());
                    buffered_segments += segs.size();
                }
             }
        }

        if (buffered_segments >= BUFFER_FLUSH_THRESHOLD) {
            flush_segment_buffer(data_fd, segment_buffer, block_infos);
            buffered_segments = 0;
        }

        if (total_reads >= next_milestone) {
            auto now = std::chrono::high_resolution_clock::now();
            std::chrono::duration<double> elapsed = now - start_time;
            std::cout << total_reads << " reads processed | " << std::fixed << std::setprecision(1) << elapsed.count() << " seconds" << std::endl;
            next_milestone += milestone_step;
        }
    }

    flush_segment_buffer(data_fd, segment_buffer, block_infos);
    close(data_fd);

    auto end_time = std::chrono::high_resolution_clock::now();
    std::chrono::duration<double> total_elapsed = end_time - start_time;

    std::cout << "\nFinal Summary:" << std::endl;
    std::cout << "  Total reads processed: " << total_reads << std::endl;
    std::cout << "  Nodes included: " << block_infos.size() << std::endl;
    std::cout << "  Elapsed time: " << std::fixed << std::setprecision(2) << total_elapsed.count() << " seconds" << std::endl;
}